### ISSUE TITLE
Repeated downloading for an updated file on Windows

### ISSUE THREAD

**Issue by williamqwu** [BoYanZh/Canvas-Syncer#10]
### Current Situation

When a file is updated by the teaching group on canvas, the local file should be updated. Canvassyncer 1.2.4 will first rename the old local file, then download the new file from canvas. However, canvassyncer compares LocalCreatedTime with RemoteModifiedTime to see whether the local file needs an update. Let's assume that RemoteCreatedTime=0000, LocalCreatedTime=0000 (exactly the same as the remote file), LocalModifiedTime=0010 (when you add some annotations on it). Now the teaching group change the file a little bit and upload it again on canvas, but since there is no re-creation of the file, RemoteCreatedTime remains the same (i.e., 0000). In this case, even though the remote updated file has been downloaded again, LocalCreatedTime stays the same. In this case, the user will be prompted the update info over and over again.

### Possible Solution

Changing `getctime` in line 295 into `getmtime` will help solve the problem temporarily. However, when LocalModifiedTime is ahead of RemoteModifiedTime, the updated version of the file will never be downloaded.

Another solution is to change the file creation date after updating the local file. However, it certainly requires a bit more code (and probably with some cross-platform issues). I've attached a link here that will probably help: https://stackoverflow.com/questions/4996405/how-do-i-change-the-file-creation-date-of-a-windows-file

Sincerely,
matrixpecker

**Comment by walwan** [comment]
Well, PERSONALLY, I think the job of a file-syncer is just ensuring the local files are identical with those on the remote. Therefore, directly annotate or modify synchronized files may be considered as a unexpected or improper use of the program. Perhaps, just check the local modified time will work.

**Comment by walwan** [comment]
I have made this change on [my forked repository](https://github.com/walwan/Canvas-Syncer) in the "fixrepeatupdatefile" branch (with some updates compared with the newest packaged version)

**Comment by BoYanZh** [comment]
I am not sure whether it is solved now?

**Comment by walwan** [comment]
I think this has been fixed or it won't be a problem since the program first renames the old file and then creates a new file and thus the new file's creation time will be the current time.
