### ISSUE TITLE
Optimize Configuration Logic

### ISSUE THREAD

**Issue by kx-Huang** [BoYanZh/Canvas-Syncer#24]
- Problem: Once course code and course ID were configured in the past, they would be saved as "default", which is inconvenient for the coming new configuration, since I have to input both course code and course ID at the same time to override the "default", otherwise an error would occur.

- One possible solution: adding the features which allows user to override "default" to blank or directly delete them, for example, by inputting "none".

**Comment by wznmickey** [comment]
You can search the config file and directly change the config rather than use the script to change,
