### ISSUE TITLE
Two way sync?

### ISSUE THREAD

**Issue by stanstrup** [BoYanZh/Canvas-Syncer#30]
As a teacher it could be nice if there was a way to sync with a local folder, such that my changes gets automatically updated.

**Comment by BoYanZh** [comment]
Good point! But as a student, sometimes a teaching assistant, I have few chances to upload files to Canvas. I have no way to test that feature. Even if I upload the files and then immediately delete them, students will still receive emails about file uploading. I am afraid I can not help you :-(, but I think the code in this project can be modified into an uploader with some minor modifications.
