### ISSUE TITLE
Further possiblity about canvassyncer?

### ISSUE THREAD

**Issue by jhinpan** [BoYanZh/Canvas-Syncer#41]
First of all, thank you a lot for your development of canvassyncer!! It helps me greatly in my past two-year JI life. Now I am in Umich, thus I wonder is there anything like changing the API such that it can become the canvassyncer for Umich? And I also wonder is there any good syncer for downloading the public GoogleDrive file which we student don't have the permission to change it. All we can do is to save them again into our local drive, which is really boring and frustrating. Sorry to bother you for that!!

**Comment by BoYanZh** [comment]
Glad to hel. :-)
For canvassyncer in Umich, you just need to reconfigure canvas URL to https://umich.instructure.com and enter the course codes and course IDs, then it will work.
For Google Drive, maybe you can use https://rclone.org/drive/ to sync files, I am not sure about that.

**Comment by jhinpan** [comment]
Thanks very much! I will try both of them lol.
