### ISSUE TITLE
Fail to download file when HTTP response is 302

### ISSUE THREAD

**Issue by walwan** [BoYanZh/Canvas-Syncer#46]
I occasionally will encounter "Fail to download these files" error. The printed out link can be manually opened and will give the correct file.
I try to use wget to download a link and found the first response is 302. From line 36 in __mian__.py, probably the program think the download fails because response code is not 200.
I am using UM canvas so the setup might be a bit different.
Thanks in advance.

**Comment by BoYanZh** [comment]
Done, fixed in 124cdafc703033e6b31cc75d007f3812709f8a18.

**Comment by walwan** [comment]
Sorry to bring this up again. The current code can download a file, but it only contains a simple html page that guides the user to the new location:

```html
<html><body>You are being <a href="https://a1770-26752971.cluster32.canvas-user-content.com/files/xxxxxxxxxxxxx/download?download_frd=1&amp;verifier=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">redirected</a>.</body></html>
```

**Comment by BoYanZh** [comment]
Does it give a 3xx http status code?

**Comment by walwan** [comment]
yes, it replied with code 302.

> Get https://umich.instructure.com/files/X/download?download_frd=1&verifier=X replied with HTTP code 302!

**Comment by BoYanZh** [comment]
It should work now with 4682d025fa819486784f0143f3abeb1b43dde714.

**Comment by walwan** [comment]
Thanks, this solved the problem.

**Comment by wznmickey** [comment]
自动回复：已收到，谢谢。
