### ISSUE TITLE
Adding new functions about submitting assignments

### ISSUE THREAD

**Issue by lrq619** [BoYanZh/Canvas-Syncer#7]
Actually I'm also writing a python script which aims to submit assignments automatically. For example, if I input VP250_Assignment2_xxx, it will automatically log in to canvas and submit it to the corresponding courses, corresponding assignments.

I'v found your script's function is very similar to mine, though I don't see the automatical submitting function. So if you want to add that function to your program, please contact me, I can simply add my code to yours and make it a better one.

The main part of my python code is basically done, now I'm writing a GUI for it both on Windows and Linux, also if you want a GUI, I can also make some contributions.

**Comment by BoYanZh** [comment]
OK. But I think auto submitting is not a heavy requirement for me. You may create your own repo for this job.

You are welcome to PR for the GUI part or any other improvement.
