### ISSUE TITLE
Next launch after error still shows error

### ISSUE THREAD

**Issue by yihuajack** [BoYanZh/Canvas-Syncer#8]
If there was ConnectionError or Exception but not KeyboardInterrupt or "Error: PermissionError" for the first launch, the program will print the error and exit. However, for the next launch, just as the program launches it still just print the error without any inputs. The problem occurs for both Windows 10 and WSL 1 Ubuntu 20.04 LTS:
![Canvas-Syncer Issue #4](https://user-images.githubusercontent.com/23608500/92575453-ea7b2800-f2ba-11ea-97b9-5971fc75afd7.png)
![Canvas-Syncer Issue #4 (2)](https://user-images.githubusercontent.com/23608500/92849999-82dded80-f41e-11ea-8e45-5e00ccad8012.png)
Btw, if directly launching from canvassyncer.exe in Windows, the printed error information will show for a very short time interval before exit so that it could not be seen. Is there any way to pause it before exit giving consideration to system compatibility so that Windows users do not need to run it in cmd or pwsh?

**Comment by BoYanZh** [comment]
Would you please update to v1.2.7 with `-d` option for detailed error information? I need more information.

For the second question, you can wrap the calling of `canvassyncer` in a batch file with a `pause` in the end of the batch file.

**Comment by yihuajack** [comment]
I have updated to 1.2.7 version in WSL 1 Ubuntu. To create an error I input a wrong Canvas access token, with other input correct, then one more problem occurs that a percent sign (%) is printed after "Getting course IDs..." instead of the error information in ZSH (in Bash the error information is correctly printed). Still, when trying to rerun "canvassyncer -d" the program started from the previous error operation as the following screenshot shows:
![Canvas-Syncer Issue #4 (3)](https://user-images.githubusercontent.com/23608500/92879112-54bcd580-f43f-11ea-9ca5-e451f2cbb261.png)

**Comment by yihuajack** [comment]
The problem is caused by the hidden file `.canvassyncer.json` located in `~/.local/lib/python3.8/site-packages/canvassyncer` for WSL 1 Ubuntu. I think the program may not always start from the state defined in `.canvassyncer.json` every time it runs even when the program runs correctly (which may mean that users could only sync one course for one generation of profile?), which is quite inconvenient for users, for if they want to refresh the program they have to manually find and delete (or edit) the file.

**Comment by BoYanZh** [comment]
Sorry I upload v1.2.7 mistakenly without printing the invalid token error, now v1.2.9 has fixed it. I think you should check your network when facing such connection error. And I also do not think that anything happens like "the program started from the previous error operation". It just gives the same result while facing the same error.

What's more, the `.canvassyncer.json` is the setting file for canvassyncer and no matter where you call the script, it will be read from where the script is located, which is `~/.local/lib/python3.8/site-packages/canvassyncer` in your case, by default. I do not think I should show it to common users. You have `-r` option and `-p` option which is enough.

And btw, course code and course ID are not both required for one course.

**Comment by yihuajack** [comment]
Thank you for reminding me the optional arguments! Maybe putting them into README instructions is considerable.
